/*
 * This file is generated by jOOQ.
 */
package com.jiangtj.demovdsegf.jooq.performance_schema.tables;


import com.jiangtj.demovdsegf.jooq.performance_schema.PerformanceSchema;
import com.jiangtj.demovdsegf.jooq.performance_schema.tables.records.GlobalVariablesRecord;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableOptions;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class GlobalVariables extends TableImpl<GlobalVariablesRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of
     * <code>performance_schema.global_variables</code>
     */
    public static final GlobalVariables GLOBAL_VARIABLES = new GlobalVariables();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<GlobalVariablesRecord> getRecordType() {
        return GlobalVariablesRecord.class;
    }

    private GlobalVariables(Name alias, Table<GlobalVariablesRecord> aliased) {
        this(alias, aliased, null);
    }

    private GlobalVariables(Name alias, Table<GlobalVariablesRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    /**
     * Create an aliased <code>performance_schema.global_variables</code> table
     * reference
     */
    public GlobalVariables(String alias) {
        this(DSL.name(alias), GLOBAL_VARIABLES);
    }

    /**
     * Create an aliased <code>performance_schema.global_variables</code> table
     * reference
     */
    public GlobalVariables(Name alias) {
        this(alias, GLOBAL_VARIABLES);
    }

    /**
     * Create a <code>performance_schema.global_variables</code> table reference
     */
    public GlobalVariables() {
        this(DSL.name("global_variables"), null);
    }

    public <O extends Record> GlobalVariables(Table<O> child, ForeignKey<O, GlobalVariablesRecord> key) {
        super(child, key, GLOBAL_VARIABLES);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : PerformanceSchema.PERFORMANCE_SCHEMA;
    }

    @Override
    public GlobalVariables as(String alias) {
        return new GlobalVariables(DSL.name(alias), this);
    }

    @Override
    public GlobalVariables as(Name alias) {
        return new GlobalVariables(alias, this);
    }

    @Override
    public GlobalVariables as(Table<?> alias) {
        return new GlobalVariables(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public GlobalVariables rename(String name) {
        return new GlobalVariables(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public GlobalVariables rename(Name name) {
        return new GlobalVariables(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public GlobalVariables rename(Table<?> name) {
        return new GlobalVariables(name.getQualifiedName(), null);
    }
}
