/*
 * This file is generated by jOOQ.
 */
package com.jiangtj.demovdsegf.jooq.performance_schema.tables;


import com.jiangtj.demovdsegf.jooq.performance_schema.PerformanceSchema;
import com.jiangtj.demovdsegf.jooq.performance_schema.tables.records.PersistedVariablesRecord;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableOptions;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class PersistedVariables extends TableImpl<PersistedVariablesRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of
     * <code>performance_schema.persisted_variables</code>
     */
    public static final PersistedVariables PERSISTED_VARIABLES = new PersistedVariables();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<PersistedVariablesRecord> getRecordType() {
        return PersistedVariablesRecord.class;
    }

    private PersistedVariables(Name alias, Table<PersistedVariablesRecord> aliased) {
        this(alias, aliased, null);
    }

    private PersistedVariables(Name alias, Table<PersistedVariablesRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    /**
     * Create an aliased <code>performance_schema.persisted_variables</code>
     * table reference
     */
    public PersistedVariables(String alias) {
        this(DSL.name(alias), PERSISTED_VARIABLES);
    }

    /**
     * Create an aliased <code>performance_schema.persisted_variables</code>
     * table reference
     */
    public PersistedVariables(Name alias) {
        this(alias, PERSISTED_VARIABLES);
    }

    /**
     * Create a <code>performance_schema.persisted_variables</code> table
     * reference
     */
    public PersistedVariables() {
        this(DSL.name("persisted_variables"), null);
    }

    public <O extends Record> PersistedVariables(Table<O> child, ForeignKey<O, PersistedVariablesRecord> key) {
        super(child, key, PERSISTED_VARIABLES);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : PerformanceSchema.PERFORMANCE_SCHEMA;
    }

    @Override
    public PersistedVariables as(String alias) {
        return new PersistedVariables(DSL.name(alias), this);
    }

    @Override
    public PersistedVariables as(Name alias) {
        return new PersistedVariables(alias, this);
    }

    @Override
    public PersistedVariables as(Table<?> alias) {
        return new PersistedVariables(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public PersistedVariables rename(String name) {
        return new PersistedVariables(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public PersistedVariables rename(Name name) {
        return new PersistedVariables(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public PersistedVariables rename(Table<?> name) {
        return new PersistedVariables(name.getQualifiedName(), null);
    }
}
