/*
 * This file is generated by jOOQ.
 */
package com.jiangtj.demovdsegf.jooq.performance_schema.tables;


import com.jiangtj.demovdsegf.jooq.performance_schema.PerformanceSchema;
import com.jiangtj.demovdsegf.jooq.performance_schema.tables.records.SessionAccountConnectAttrsRecord;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableOptions;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class SessionAccountConnectAttrs extends TableImpl<SessionAccountConnectAttrsRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of
     * <code>performance_schema.session_account_connect_attrs</code>
     */
    public static final SessionAccountConnectAttrs SESSION_ACCOUNT_CONNECT_ATTRS = new SessionAccountConnectAttrs();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<SessionAccountConnectAttrsRecord> getRecordType() {
        return SessionAccountConnectAttrsRecord.class;
    }

    private SessionAccountConnectAttrs(Name alias, Table<SessionAccountConnectAttrsRecord> aliased) {
        this(alias, aliased, null);
    }

    private SessionAccountConnectAttrs(Name alias, Table<SessionAccountConnectAttrsRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    /**
     * Create an aliased
     * <code>performance_schema.session_account_connect_attrs</code> table
     * reference
     */
    public SessionAccountConnectAttrs(String alias) {
        this(DSL.name(alias), SESSION_ACCOUNT_CONNECT_ATTRS);
    }

    /**
     * Create an aliased
     * <code>performance_schema.session_account_connect_attrs</code> table
     * reference
     */
    public SessionAccountConnectAttrs(Name alias) {
        this(alias, SESSION_ACCOUNT_CONNECT_ATTRS);
    }

    /**
     * Create a <code>performance_schema.session_account_connect_attrs</code>
     * table reference
     */
    public SessionAccountConnectAttrs() {
        this(DSL.name("session_account_connect_attrs"), null);
    }

    public <O extends Record> SessionAccountConnectAttrs(Table<O> child, ForeignKey<O, SessionAccountConnectAttrsRecord> key) {
        super(child, key, SESSION_ACCOUNT_CONNECT_ATTRS);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : PerformanceSchema.PERFORMANCE_SCHEMA;
    }

    @Override
    public SessionAccountConnectAttrs as(String alias) {
        return new SessionAccountConnectAttrs(DSL.name(alias), this);
    }

    @Override
    public SessionAccountConnectAttrs as(Name alias) {
        return new SessionAccountConnectAttrs(alias, this);
    }

    @Override
    public SessionAccountConnectAttrs as(Table<?> alias) {
        return new SessionAccountConnectAttrs(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public SessionAccountConnectAttrs rename(String name) {
        return new SessionAccountConnectAttrs(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public SessionAccountConnectAttrs rename(Name name) {
        return new SessionAccountConnectAttrs(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public SessionAccountConnectAttrs rename(Table<?> name) {
        return new SessionAccountConnectAttrs(name.getQualifiedName(), null);
    }
}
