/*
 * This file is generated by jOOQ.
 */
package com.jiangtj.demovdsegf.jooq.performance_schema.tables;


import com.jiangtj.demovdsegf.jooq.performance_schema.PerformanceSchema;
import com.jiangtj.demovdsegf.jooq.performance_schema.tables.records.VariablesInfoRecord;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableOptions;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class VariablesInfo extends TableImpl<VariablesInfoRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>performance_schema.variables_info</code>
     */
    public static final VariablesInfo VARIABLES_INFO = new VariablesInfo();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<VariablesInfoRecord> getRecordType() {
        return VariablesInfoRecord.class;
    }

    private VariablesInfo(Name alias, Table<VariablesInfoRecord> aliased) {
        this(alias, aliased, null);
    }

    private VariablesInfo(Name alias, Table<VariablesInfoRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    /**
     * Create an aliased <code>performance_schema.variables_info</code> table
     * reference
     */
    public VariablesInfo(String alias) {
        this(DSL.name(alias), VARIABLES_INFO);
    }

    /**
     * Create an aliased <code>performance_schema.variables_info</code> table
     * reference
     */
    public VariablesInfo(Name alias) {
        this(alias, VARIABLES_INFO);
    }

    /**
     * Create a <code>performance_schema.variables_info</code> table reference
     */
    public VariablesInfo() {
        this(DSL.name("variables_info"), null);
    }

    public <O extends Record> VariablesInfo(Table<O> child, ForeignKey<O, VariablesInfoRecord> key) {
        super(child, key, VARIABLES_INFO);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : PerformanceSchema.PERFORMANCE_SCHEMA;
    }

    @Override
    public VariablesInfo as(String alias) {
        return new VariablesInfo(DSL.name(alias), this);
    }

    @Override
    public VariablesInfo as(Name alias) {
        return new VariablesInfo(alias, this);
    }

    @Override
    public VariablesInfo as(Table<?> alias) {
        return new VariablesInfo(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public VariablesInfo rename(String name) {
        return new VariablesInfo(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public VariablesInfo rename(Name name) {
        return new VariablesInfo(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public VariablesInfo rename(Table<?> name) {
        return new VariablesInfo(name.getQualifiedName(), null);
    }
}
