/*
 * This file is generated by jOOQ.
 */
package com.jiangtj.demovdsegf.jooq.performance_schema.tables.records;


import com.jiangtj.demovdsegf.jooq.performance_schema.tables.GlobalVariables;

import org.jooq.impl.TableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class GlobalVariablesRecord extends TableRecordImpl<GlobalVariablesRecord> {

    private static final long serialVersionUID = 1L;

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached GlobalVariablesRecord
     */
    public GlobalVariablesRecord() {
        super(GlobalVariables.GLOBAL_VARIABLES);
    }
}
