/*
 * This file is generated by jOOQ.
 */
package com.jiangtj.demovdsegf.jooq.performance_schema.tables.records;


import com.jiangtj.demovdsegf.jooq.performance_schema.tables.PersistedVariables;

import org.jooq.impl.TableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class PersistedVariablesRecord extends TableRecordImpl<PersistedVariablesRecord> {

    private static final long serialVersionUID = 1L;

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached PersistedVariablesRecord
     */
    public PersistedVariablesRecord() {
        super(PersistedVariables.PERSISTED_VARIABLES);
    }
}
