/*
 * This file is generated by jOOQ.
 */
package com.jiangtj.demovdsegf.jooq.performance_schema.tables.records;


import com.jiangtj.demovdsegf.jooq.performance_schema.tables.SessionAccountConnectAttrs;

import org.jooq.impl.TableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class SessionAccountConnectAttrsRecord extends TableRecordImpl<SessionAccountConnectAttrsRecord> {

    private static final long serialVersionUID = 1L;

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached SessionAccountConnectAttrsRecord
     */
    public SessionAccountConnectAttrsRecord() {
        super(SessionAccountConnectAttrs.SESSION_ACCOUNT_CONNECT_ATTRS);
    }
}
