/*
 * This file is generated by jOOQ.
 */
package com.jiangtj.demovdsegf.jooq.performance_schema.tables.records;


import com.jiangtj.demovdsegf.jooq.performance_schema.tables.VariablesInfo;

import org.jooq.impl.TableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class VariablesInfoRecord extends TableRecordImpl<VariablesInfoRecord> {

    private static final long serialVersionUID = 1L;

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached VariablesInfoRecord
     */
    public VariablesInfoRecord() {
        super(VariablesInfo.VARIABLES_INFO);
    }
}
