/*
 * This file is generated by jOOQ.
 */
package com.jiangtj.demovdsegf.jooq.performance_schema;


import com.jiangtj.demovdsegf.jooq.DefaultCatalog;
import com.jiangtj.demovdsegf.jooq.performance_schema.tables.GlobalStatus;
import com.jiangtj.demovdsegf.jooq.performance_schema.tables.GlobalVariables;
import com.jiangtj.demovdsegf.jooq.performance_schema.tables.PersistedVariables;
import com.jiangtj.demovdsegf.jooq.performance_schema.tables.Processlist;
import com.jiangtj.demovdsegf.jooq.performance_schema.tables.SessionAccountConnectAttrs;
import com.jiangtj.demovdsegf.jooq.performance_schema.tables.SessionStatus;
import com.jiangtj.demovdsegf.jooq.performance_schema.tables.SessionVariables;
import com.jiangtj.demovdsegf.jooq.performance_schema.tables.VariablesInfo;

import java.util.Arrays;
import java.util.List;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class PerformanceSchema extends SchemaImpl {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>performance_schema</code>
     */
    public static final PerformanceSchema PERFORMANCE_SCHEMA = new PerformanceSchema();

    /**
     * The table <code>performance_schema.global_status</code>.
     */
    public final GlobalStatus GLOBAL_STATUS = GlobalStatus.GLOBAL_STATUS;

    /**
     * The table <code>performance_schema.global_variables</code>.
     */
    public final GlobalVariables GLOBAL_VARIABLES = GlobalVariables.GLOBAL_VARIABLES;

    /**
     * The table <code>performance_schema.persisted_variables</code>.
     */
    public final PersistedVariables PERSISTED_VARIABLES = PersistedVariables.PERSISTED_VARIABLES;

    /**
     * The table <code>performance_schema.processlist</code>.
     */
    public final Processlist PROCESSLIST = Processlist.PROCESSLIST;

    /**
     * The table <code>performance_schema.session_account_connect_attrs</code>.
     */
    public final SessionAccountConnectAttrs SESSION_ACCOUNT_CONNECT_ATTRS = SessionAccountConnectAttrs.SESSION_ACCOUNT_CONNECT_ATTRS;

    /**
     * The table <code>performance_schema.session_status</code>.
     */
    public final SessionStatus SESSION_STATUS = SessionStatus.SESSION_STATUS;

    /**
     * The table <code>performance_schema.session_variables</code>.
     */
    public final SessionVariables SESSION_VARIABLES = SessionVariables.SESSION_VARIABLES;

    /**
     * The table <code>performance_schema.variables_info</code>.
     */
    public final VariablesInfo VARIABLES_INFO = VariablesInfo.VARIABLES_INFO;

    /**
     * No further instances allowed
     */
    private PerformanceSchema() {
        super("performance_schema", null);
    }


    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        return Arrays.asList(
            GlobalStatus.GLOBAL_STATUS,
            GlobalVariables.GLOBAL_VARIABLES,
            PersistedVariables.PERSISTED_VARIABLES,
            Processlist.PROCESSLIST,
            SessionAccountConnectAttrs.SESSION_ACCOUNT_CONNECT_ATTRS,
            SessionStatus.SESSION_STATUS,
            SessionVariables.SESSION_VARIABLES,
            VariablesInfo.VARIABLES_INFO
        );
    }
}
