/*
 * This file is generated by jOOQ.
 */
package com.jiangtj.demovdsegf.jooq.performance_schema;


import com.jiangtj.demovdsegf.jooq.performance_schema.tables.GlobalStatus;
import com.jiangtj.demovdsegf.jooq.performance_schema.tables.GlobalVariables;
import com.jiangtj.demovdsegf.jooq.performance_schema.tables.PersistedVariables;
import com.jiangtj.demovdsegf.jooq.performance_schema.tables.Processlist;
import com.jiangtj.demovdsegf.jooq.performance_schema.tables.SessionAccountConnectAttrs;
import com.jiangtj.demovdsegf.jooq.performance_schema.tables.SessionStatus;
import com.jiangtj.demovdsegf.jooq.performance_schema.tables.SessionVariables;
import com.jiangtj.demovdsegf.jooq.performance_schema.tables.VariablesInfo;


/**
 * Convenience access to all tables in performance_schema.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Tables {

    /**
     * The table <code>performance_schema.global_status</code>.
     */
    public static final GlobalStatus GLOBAL_STATUS = GlobalStatus.GLOBAL_STATUS;

    /**
     * The table <code>performance_schema.global_variables</code>.
     */
    public static final GlobalVariables GLOBAL_VARIABLES = GlobalVariables.GLOBAL_VARIABLES;

    /**
     * The table <code>performance_schema.persisted_variables</code>.
     */
    public static final PersistedVariables PERSISTED_VARIABLES = PersistedVariables.PERSISTED_VARIABLES;

    /**
     * The table <code>performance_schema.processlist</code>.
     */
    public static final Processlist PROCESSLIST = Processlist.PROCESSLIST;

    /**
     * The table <code>performance_schema.session_account_connect_attrs</code>.
     */
    public static final SessionAccountConnectAttrs SESSION_ACCOUNT_CONNECT_ATTRS = SessionAccountConnectAttrs.SESSION_ACCOUNT_CONNECT_ATTRS;

    /**
     * The table <code>performance_schema.session_status</code>.
     */
    public static final SessionStatus SESSION_STATUS = SessionStatus.SESSION_STATUS;

    /**
     * The table <code>performance_schema.session_variables</code>.
     */
    public static final SessionVariables SESSION_VARIABLES = SessionVariables.SESSION_VARIABLES;

    /**
     * The table <code>performance_schema.variables_info</code>.
     */
    public static final VariablesInfo VARIABLES_INFO = VariablesInfo.VARIABLES_INFO;
}
