/*
 * This file is generated by jOOQ.
 */
package com.jiangtj.demovdsegf.jooq.mydatabase;


import com.jiangtj.demovdsegf.jooq.mydatabase.tables.AdminUser;
import com.jiangtj.demovdsegf.jooq.mydatabase.tables.FlywaySchemaHistory;

import org.jooq.Index;
import org.jooq.OrderField;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;


/**
 * A class modelling indexes of tables in mydatabase.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Indexes {

    // -------------------------------------------------------------------------
    // INDEX definitions
    // -------------------------------------------------------------------------

    public static final Index FLYWAY_SCHEMA_HISTORY_FLYWAY_SCHEMA_HISTORY_S_IDX = Internal.createIndex(DSL.name("flyway_schema_history_s_idx"), FlywaySchemaHistory.FLYWAY_SCHEMA_HISTORY, new OrderField[] { FlywaySchemaHistory.FLYWAY_SCHEMA_HISTORY.SUCCESS }, false);
    public static final Index ADMIN_USER_K_NAME = Internal.createIndex(DSL.name("k_name"), AdminUser.ADMIN_USER, new OrderField[] { AdminUser.ADMIN_USER.USERNAME }, false);
}
