/*
 * This file is generated by jOOQ.
 */
package com.jiangtj.demovdsegf.jooq.mydatabase;


import com.jiangtj.demovdsegf.jooq.DefaultCatalog;
import com.jiangtj.demovdsegf.jooq.mydatabase.tables.AdminUser;
import com.jiangtj.demovdsegf.jooq.mydatabase.tables.FlywaySchemaHistory;

import java.util.Arrays;
import java.util.List;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Mydatabase extends SchemaImpl {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>mydatabase</code>
     */
    public static final Mydatabase MYDATABASE = new Mydatabase();

    /**
     * 管理员帐号
     */
    public final AdminUser ADMIN_USER = AdminUser.ADMIN_USER;

    /**
     * The table <code>mydatabase.flyway_schema_history</code>.
     */
    public final FlywaySchemaHistory FLYWAY_SCHEMA_HISTORY = FlywaySchemaHistory.FLYWAY_SCHEMA_HISTORY;

    /**
     * No further instances allowed
     */
    private Mydatabase() {
        super("mydatabase", null);
    }


    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        return Arrays.asList(
            AdminUser.ADMIN_USER,
            FlywaySchemaHistory.FLYWAY_SCHEMA_HISTORY
        );
    }
}
