/*
 * This file is generated by jOOQ.
 */
package com.jiangtj.demovdsegf.jooq.mydatabase;


import com.jiangtj.demovdsegf.jooq.mydatabase.tables.AdminUser;
import com.jiangtj.demovdsegf.jooq.mydatabase.tables.FlywaySchemaHistory;


/**
 * Convenience access to all tables in mydatabase.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Tables {

    /**
     * 管理员帐号
     */
    public static final AdminUser ADMIN_USER = AdminUser.ADMIN_USER;

    /**
     * The table <code>mydatabase.flyway_schema_history</code>.
     */
    public static final FlywaySchemaHistory FLYWAY_SCHEMA_HISTORY = FlywaySchemaHistory.FLYWAY_SCHEMA_HISTORY;
}
