/*
 * This file is generated by jOOQ.
 */
package com.jiangtj.demovdsegf.jooq.information_schema.tables;


import com.jiangtj.demovdsegf.jooq.information_schema.InformationSchema;
import com.jiangtj.demovdsegf.jooq.information_schema.tables.records.TablespacesExtensionsRecord;

import java.util.function.Function;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Function2;
import org.jooq.JSON;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Records;
import org.jooq.Row2;
import org.jooq.Schema;
import org.jooq.SelectField;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class TablespacesExtensions extends TableImpl<TablespacesExtensionsRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of
     * <code>information_schema.TABLESPACES_EXTENSIONS</code>
     */
    public static final TablespacesExtensions TABLESPACES_EXTENSIONS = new TablespacesExtensions();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<TablespacesExtensionsRecord> getRecordType() {
        return TablespacesExtensionsRecord.class;
    }

    /**
     * The column
     * <code>information_schema.TABLESPACES_EXTENSIONS.TABLESPACE_NAME</code>.
     */
    public final TableField<TablespacesExtensionsRecord, String> TABLESPACE_NAME = createField(DSL.name("TABLESPACE_NAME"), SQLDataType.VARCHAR(268).nullable(false), this, "");

    /**
     * The column
     * <code>information_schema.TABLESPACES_EXTENSIONS.ENGINE_ATTRIBUTE</code>.
     */
    public final TableField<TablespacesExtensionsRecord, JSON> ENGINE_ATTRIBUTE = createField(DSL.name("ENGINE_ATTRIBUTE"), SQLDataType.JSON, this, "");

    private TablespacesExtensions(Name alias, Table<TablespacesExtensionsRecord> aliased) {
        this(alias, aliased, null);
    }

    private TablespacesExtensions(Name alias, Table<TablespacesExtensionsRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    /**
     * Create an aliased <code>information_schema.TABLESPACES_EXTENSIONS</code>
     * table reference
     */
    public TablespacesExtensions(String alias) {
        this(DSL.name(alias), TABLESPACES_EXTENSIONS);
    }

    /**
     * Create an aliased <code>information_schema.TABLESPACES_EXTENSIONS</code>
     * table reference
     */
    public TablespacesExtensions(Name alias) {
        this(alias, TABLESPACES_EXTENSIONS);
    }

    /**
     * Create a <code>information_schema.TABLESPACES_EXTENSIONS</code> table
     * reference
     */
    public TablespacesExtensions() {
        this(DSL.name("TABLESPACES_EXTENSIONS"), null);
    }

    public <O extends Record> TablespacesExtensions(Table<O> child, ForeignKey<O, TablespacesExtensionsRecord> key) {
        super(child, key, TABLESPACES_EXTENSIONS);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : InformationSchema.INFORMATION_SCHEMA;
    }

    @Override
    public TablespacesExtensions as(String alias) {
        return new TablespacesExtensions(DSL.name(alias), this);
    }

    @Override
    public TablespacesExtensions as(Name alias) {
        return new TablespacesExtensions(alias, this);
    }

    @Override
    public TablespacesExtensions as(Table<?> alias) {
        return new TablespacesExtensions(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public TablespacesExtensions rename(String name) {
        return new TablespacesExtensions(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public TablespacesExtensions rename(Name name) {
        return new TablespacesExtensions(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public TablespacesExtensions rename(Table<?> name) {
        return new TablespacesExtensions(name.getQualifiedName(), null);
    }

    // -------------------------------------------------------------------------
    // Row2 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row2<String, JSON> fieldsRow() {
        return (Row2) super.fieldsRow();
    }

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Function)}.
     */
    public <U> SelectField<U> mapping(Function2<? super String, ? super JSON, ? extends U> from) {
        return convertFrom(Records.mapping(from));
    }

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Class,
     * Function)}.
     */
    public <U> SelectField<U> mapping(Class<U> toType, Function2<? super String, ? super JSON, ? extends U> from) {
        return convertFrom(toType, Records.mapping(from));
    }
}
