/*
 * This file is generated by jOOQ.
 */
package com.jiangtj.testmvn.demovdsegf.jooq.tables.pojos;


import java.io.Serializable;
import java.time.LocalDateTime;


/**
 * 水果
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public record Foods(
    Long id,
    LocalDateTime createTime,
    LocalDateTime modifyTime,
    String name,
    Integer price,
    Byte isDeleted
) implements Serializable {

    private static final long serialVersionUID = 1L;


    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final Foods other = (Foods) obj;
        if (this.id == null) {
            if (other.id != null)
                return false;
        }
        else if (!this.id.equals(other.id))
            return false;
        if (this.createTime == null) {
            if (other.createTime != null)
                return false;
        }
        else if (!this.createTime.equals(other.createTime))
            return false;
        if (this.modifyTime == null) {
            if (other.modifyTime != null)
                return false;
        }
        else if (!this.modifyTime.equals(other.modifyTime))
            return false;
        if (this.name == null) {
            if (other.name != null)
                return false;
        }
        else if (!this.name.equals(other.name))
            return false;
        if (this.price == null) {
            if (other.price != null)
                return false;
        }
        else if (!this.price.equals(other.price))
            return false;
        if (this.isDeleted == null) {
            if (other.isDeleted != null)
                return false;
        }
        else if (!this.isDeleted.equals(other.isDeleted))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.id == null) ? 0 : this.id.hashCode());
        result = prime * result + ((this.createTime == null) ? 0 : this.createTime.hashCode());
        result = prime * result + ((this.modifyTime == null) ? 0 : this.modifyTime.hashCode());
        result = prime * result + ((this.name == null) ? 0 : this.name.hashCode());
        result = prime * result + ((this.price == null) ? 0 : this.price.hashCode());
        result = prime * result + ((this.isDeleted == null) ? 0 : this.isDeleted.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Foods (");

        sb.append(id);
        sb.append(", ").append(createTime);
        sb.append(", ").append(modifyTime);
        sb.append(", ").append(name);
        sb.append(", ").append(price);
        sb.append(", ").append(isDeleted);

        sb.append(")");
        return sb.toString();
    }
}
