
CREATE TABLE `foods` (
    `id` BIGINT NOT NULL AUTO_INCREMENT,
    `create_time` DATETIME(0) NOT NULL DEFAULT CURRENT_TIMESTAMP(0) COMMENT '创建时间',
    `modify_time` DATETIME(0) NOT NULL DEFAULT CURRENT_TIMESTAMP(0) ON UPDATE CURRENT_TIMESTAMP(0) COMMENT '修改时间',
    `name` VARCHAR(32) NOT NULL COMMENT '名字',
    `price` INT NOT NULL COMMENT '单价',
    `is_deleted` TINYINT NOT NULL DEFAULT 0 COMMENT '是否删除 0 否 1 是',
    PRIMARY KEY (`id`) USING BTREE
) ENGINE = InnoDB COMMENT = '水果';
